Make SVE-enabled ARM64 targets in DYNAMIC_ARCH builds depend on a relatively recent compiler
xianyi/OpenBLAS pull request #3875
Opened 2022-12-25 09:26 UTC by martin-frbg

fixes #3874 (fixes #3805)

2022-12-25 14:43 UTC, Mousius approved these changes
LGTM!

2022-12-25 15:52 UTC, Mousius requested changes
Realised build was failing, so I took a deeper look into this one.

#3876 fixed the build for me @martin-frbg

2022-12-25 15:52 UTC, Mousius commented on driver/others/dynamic_arm64.c
> +#ifndef NO_SVE
Since we're aliasing these above, this isn't necessary to be guarded by `NO_SVE`?

2022-12-25 15:52 UTC, Mousius commented on driver/others/dynamic_arm64.c
> +#define gotoblas_NEOVERSEN2 gotoblas_ARMV8;
You've got some rogue semi-colons here:

```suggestion
#define gotoblas_NEOVERSEV1 gotoblas_ARMV8
#define gotoblas_NEOVERSEN2 gotoblas_ARMV8
```

2022-12-25 23:48 UTC, martin-frbg commented
Sorry for the mess, visiting family and tried to sneak in some discreet coding via the gh web editor. Will clean up ASAP

2022-12-26 00:21 UTC, Mousius commented
> Sorry for the mess, visiting family and tried to sneak in some discreet coding via the gh web editor. Will clean up ASAP

No worries, just here to help 😸

2022-12-30 16:53 UTC, martin-frbg commented
This has now uncovered a latent bug in the MSA support detection/handling for MIPS. To be continued, hopefully later today

2022-12-31 11:06 UTC, martin-frbg commented
mips msa fixes to go into a separate PR, merging to get this out if the way

2022-12-31 11:07 UTC, merged